language: node_js
node_js:
- node
- 8
deploy:
  provider: npm
  email: "$YOUR_EMAIL_ADDRESS"
  api_key:
    secure: AKLNhreMQdGaf8s4EIxex/5JWJ2HqdEUxTyfXj0I9LX+uAB9LUZejPv5lVyCFjIn9icdDEyIBNAlDPpnx2R4JtIo+asnyE8VG2EpPFMoKQZDqa0zdHTraGE8d4B/z4OPJVCDz6fa/HHkGnhRkRZ3wBD35Ra8vR47FRNuLInYs53Z4CK2UF5ucHgRupM1V+E7BTVEHsm8ZZIc0P5rR4qzm4Jzcwt4mOjcVgkTUHs0RKDGvwU8menUlDOgnx2E4aUO27HURjTiXsx7DJv6hEmKIDOSawKPmJu1yH5DWTG5RyYdHb80MhmkcKV4ayBD9jbqD1+yzoiVSDGAxV0jyJ4zVCumIkCpmHI2A6W9Rp3jHPxdqSXiAgKlKNjpwsV4IHjHamd7BxEKHo9vZi2AiMd+OlgPJrjksnn7A9LA/Swu9xYBbkPXsCrIFXRm1KSSAzAIdKyM9tbRMhChyJ4+JgjAwD6H8g5fzWod8JDmckFNzK2By8ABvQSe0kfB7Cuak7/teV0adwnUPLQE51BxfayFLs6Kw7kxcz26OKC2w70MWUiNkGqgc6A3W1PYjhk0fLAffKDREQWhw8S2FsaTLtVnDYNqzh/1vEN6sJ3/7rGjM8yfIoBGkytakUBn+heAtdgj7yXjLPzQUbSyrhfwukISwKI6el0O63VZt+Wy1rkY/gw=
  on:
    tags: true
    repo: up9cloud/node-opencc-cli
    branch: master
  skip_cleanup: true

